baseURL = 'https://github.com/stefanciutac/stefanciutac_devlog.git'
languageCode = 'en-gb'
title = 'Exit Code: 0'
theme = 'PaperMod'

[params]
    defaultTheme = "auto"
    showCodeCopyButtons = true
    [params.profileMode]
    enabled = true
    title = "Exit Code: 0"
    subtitle = "Documenting my struggle against GCC"
    [[params.profileMode.buttons]]
        name = "Posts"
        url = "posts"
    [[params.profileMode.buttons]]
        name = "GitHub"
        url = "https://github.com/stefanciutac"
